# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TransPlace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyStarRatingView'
  pod ‘Firebase’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Database’
  pod ‘SwiftyJSON’ 
  # Pods for TransPlace

end
